export function seedWorld(){
 const make=(id,name,type,summary,body,tags=[],properties=[])=>({id,name,type,summary,body,tags,properties,image:'',updated:Date.now()});
 return {format:'worldloom',version:1,name:'The Waking Coast',description:'A world caught between the old tides and a new dawn.',calendar:{era:'AT',months:[{name:'Thaw',days:30},{name:'Bloom',days:30},{name:'Suncrest',days:31},{name:'Ember',days:30},{name:'Harvest',days:30},{name:'Mistfall',days:31},{name:'Longnight',days:30},{name:'Stillwater',days:30}],weekdays:['First','Second','Third','Fourth','Fifth','Sixth'],currentYear:842},entities:[
 make('mira','Mira Vey','Character','A cartographer tracing the coast that no longer exists.','## A map of what was lost\nMira carries her mother’s atlas, its coastlines changing with each passing tide. She works from [[Saltglass Harbor]], under the uneasy protection of [[The Lantern Assembly]].\n\n## An unfinished promise\nFind the source of the light beneath the [[Verdant Reach]].',['Cartographer','Tideborn'],[{key:'Home',value:'Saltglass Harbor'},{key:'Age',value:'28'}]),
 make('saltglass','Saltglass Harbor','Location','A city of pale towers and bridges built above a restless sea.','## At the water’s edge\nSaltglass was rebuilt after [[The Night of Two Tides]]. Its glass lanterns shelter small colonies of [[Glasswing Moths]].\n\n## Districts\nThe Tidemarket, the Old Observatory, and the submerged bells of the eastern quarter.',['Coast','Settlement'],[{key:'Population',value:'18,400'},{key:'Climate',value:'Temperate maritime'}]),
 make('lanterns','The Lantern Assembly','Faction','Keepers of the lights, and of the histories kept in shadow.','## Purpose\nThe Assembly maintains the coastal beacons and records the movements of the sea. [[Mira Vey]] suspects their oldest charts conceal a second coastline.\n\n## Divisions\nThe Keepers guard the beacons. The Readers interpret what their light reveals.',['Keepers','Politics'],[{key:'Seat',value:'Saltglass Harbor'}]),
 make('reach','Verdant Reach','Ecology','A tidal forest where the canopy blooms beneath the water.','## A breathing landscape\nTwice a year the sea withdraws, revealing a forest of green glass and living roots. [[Glasswing Moths]] pollinate its flowers during the brief low tide.\n\n## Fragile balance\nRemoving the moths silences the forest. The [[Tideheart Compass]] points toward the oldest tree.',['Biome','Tidal forest'],[{key:'Keystone species',value:'Glasswing Moths'},{key:'Threat',value:'Salt extraction'}]),
 make('moths','Glasswing Moths','Creature','Their transparent wings hold a memory of every light they touch.','## Ecology\nNative to the [[Verdant Reach]], these moths feed on salt nectar and glow in the presence of old magic. Colonies have recently appeared in [[Saltglass Harbor]].\n\n## Behavior\nThey migrate toward submerged bells before great storms.',['Pollinator','Nocturnal'],[{key:'Habitat',value:'Tidal forests'},{key:'Diet',value:'Salt nectar'}]),
 make('compass','Tideheart Compass','Item','An instrument that points toward a place, not a direction.','## Origin\nRecovered from a wreck after [[The Night of Two Tides]]. Now carried by [[Mira Vey]].\n\nIts needle turns only when submerged in seawater.',['Relic'],[{key:'Material',value:'Brass and sea glass'}]),
 {...make('tides','The Night of Two Tides','Event','The sea rose twice. When it receded, a different coast remained.','## The turning point\nThe eastern quarter of [[Saltglass Harbor]] disappeared. [[The Lantern Assembly]] sealed the observatory’s records the following morning.',['History']),date:{year:814,month:5,day:18}},
 {...make('expedition','The First Green Expedition','Event','Mira crosses the exposed forest with a stolen chart.','[[Mira Vey]] enters the [[Verdant Reach]], carrying the [[Tideheart Compass]].',['Expedition']),date:{year:842,month:1,day:12}},
 make('lore','The Drowned Bells','Lore','What the bells remember, the sea will eventually return.','## A coastal belief\nEach submerged bell is said to hold a memory of the land before the flood. Sailors listen for them in the hours before dawn.\n\nSome say [[Glasswing Moths]] are those memories, given wings.',['Myth','Folklore'])
 ],relations:[{id:'r1',from:'mira',to:'saltglass',label:'lives in',kind:'connection'},{id:'r2',from:'mira',to:'lanterns',label:'works for',kind:'connection'},{id:'r3',from:'moths',to:'reach',label:'pollinates',kind:'connection'},{id:'r4',from:'mira',to:'compass',label:'carries',kind:'connection'},{id:'r5',from:'lanterns',to:'saltglass',label:'protects',kind:'connection'},{id:'r6',from:'tides',to:'saltglass',label:'transformed',kind:'connection'},{id:'r7',from:'expedition',to:'mira',label:'led by',kind:'connection'}],maps:[{id:'coast',name:'The Waking Coast',image:'',pins:[{id:'p1',entity:'saltglass',x:62,y:57},{id:'p2',entity:'reach',x:38,y:38}],regions:[]}],boards:[{id:'origins',name:'Threads of the coast',nodes:[{id:'n1',entity:'mira',x:90,y:160},{id:'n2',entity:'compass',x:430,y:60},{id:'n3',entity:'reach',x:780,y:230},{id:'n4',text:'What if the coast is remembering itself?\n\nFollow the moths. Listen for the bells.',x:430,y:320}]}]};
}
